- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Configura o source.list
    copy:
      content: |
        # Original APT package sources gathered by Ansible
        deb http://debian.pop-sc.rnp.br/debian buster main contrib non-free
        deb http://debian.pop-sc.rnp.br/debian buster-updates main contrib non-free
        deb http://debian.pop-sc.rnp.br/debian buster-backports main contrib non-free

        # Official Debian repositories
        deb http://deb.debian.org/debian buster main contrib non-free
        deb http://deb.debian.org/debian buster-updates main contrib non-free
        deb http://deb.debian.org/debian buster-backports main contrib non-free

        # Debian Security repository
        deb http://security.debian.org/ buster/updates main contrib non-free
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0644


  - name: update apt cache
    apt: update_cache=yes cache_valid_time=7200
    when: ansible_os_family == 'Debian'

  - name: Upgrade all packages to the latest version
    apt: name="*" state=latest
    when: ansible_os_family == 'Debian'
  
  - name: Instalar pacotes padroes - Linux
    apt: 
      name: "{{ packages }}"
      state:  latest
    vars:
      packages:
      - aptitude 
      - vim 
      - firmware-linux 
      - vlc 
      - unrar 
      - dkms 
      - ntp 
      - ssh 
      - ttf-mscorefonts-installer 
      - dia 
      - kolourpaint4 
      - kdenlive
      - kde-l10n-ptbr  
      - nmap
      - mtr
      - ntfs-3g
      - xournal
      - ipcalc
      - tcpdump
      - bash-completion
      - git
      - transmission-gtk
      - pdfshuffler
      - libnss3-tools
      - libcurl3-nss
      - firefox-esr-l10n-pt-br
      - webext-ublock-origin
      - keepassxc
      - firmware-realtek
    when: ansible_os_family == 'Debian'
  
  - name: Instala m贸dulo WL (Wireless)
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:        
      - linux-headers-{{ ansible_kernel }}
      - broadcom-sta-dkms
    when: ansible_os_family == 'Debian'
  
  - name: Remove pacotes
    apt:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:        
      - gnome-games
      - evolution
      - cheese
      - gnome-maps
      - rhythmbox
      - xterm
      - totem
      - gnome-todo
      - gnome-contacts
      - gnome-documents
    when: ansible_os_family == 'Debian'

  - name: Configura m贸dulos blacklist.conf
    copy:
      content: |
        blacklist pcspkr        
      dest: /etc/modprobe.d/blacklist.conf
      owner: root
      group: root
      mode: 0644
    when: ansible_os_family == 'Debian'

  - name: disable bluetooth on boot
    lineinfile:
      path: /etc/bluetooth/main.conf
      regexp: '^AutoEnable=true'
      backrefs: yes
      backup: yes    
      line: AutoEnable=false
    when: ansible_os_family == 'Debian'
    tags: 
    - blue

  - name: Instalar o .deb warsaw - Linux Debian
    apt:
      deb: https://cloud.gastecnologia.com.br/bb/downloads/ws/warsaw_setup64.deb
    when: ansible_distribution == 'Debian'

  - name: Install a .deb Google Chrome - Linux Debian
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    when: ansible_os_family == 'Debian'
  
  - name: Install a .deb Dropbox - Linux Debian
    apt:
      deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb
    when: ansible_os_family == 'Debian'

  - name: Adicionar a chave do reposit贸rio do docker no buster
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'buster')

  - name: Adicionar reposit贸rio do docker no buster
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
      state: present
      update_cache: yes
    when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'buster')

  - name: Instalar o docker no buster
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'buster')

  - name: Remove useless packages from the cache
    apt: autoclean=yes
    when: ansible_os_family == 'Debian'

  - name: Remove dependencies that are no longer required
    apt: autoremove=yes
    when: ansible_os_family == 'Debian'
