- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: update the apt package index i.e. apt-get update
    apt: update_cache=yes

  - name: upgrade system packages i.e. apt-get upgrade
    apt: upgrade=yes

  - name: Install a .deb Google Chrome - Linux Debian
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    when: ansible_os_family == 'Debian'
  
  - name: Install a .deb Dropbox - Linux Debian
    apt:
      deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
    when: ansible_os_family == 'Debian'
  
  - name: Instalar pacotes padroes - Linux
    apt: name={{item}} state=latest
    with_items:
      - aptitude 
      - vim 
      - firmware-linux 
      - vlc 
      - unrar 
      - dkms 
      - ntp 
      - libcurl3 
      - ssh 
      - pdfsam 
      - ttf-mscorefonts-installer 
      - dia 
      - kolourpaint4 
      - kdenlive
      - kde-l10n-ptbr  
      - openjdk-8-jre
      - icedtea-8-plugin
      - google-chrome-stable
      - nmap
      - mtr
      - ntfs-3g
      - xournal
      - ipcalc
      - tcpdump
      - bash-completion
      - git
      - transmission-gtk
    when: ansible_os_family == 'Debian'


  - name: Instalar os pacotes necessários para o warsaw
    apt: name={{item}} state=latest
    with_items:
      - libnss3-tools
      - libcurl3
    when: ansible_distribution == 'Debian'

  - name: Instalar o .deb warsaw - Linux Debian
    apt:
      deb: https://cloud.gastecnologia.com.br/bb/downloads/ws/warsaw_setup64.deb
    when: ansible_distribution == 'Debian'
