- name: Run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local

  roles:
    - firefox_java8
    # - flashplayer

  tasks:
    - name: Set sources.list
      ansible.builtin.copy:
        content: |
          deb http://br.archive.ubuntu.com/ubuntu/ mantic main restricted universe multiverse
          deb http://br.archive.ubuntu.com/ubuntu/ mantic-updates main restricted universe multiverse
          deb http://br.archive.ubuntu.com/ubuntu/ mantic-backports main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu mantic-security main restricted universe multiverse
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == 'Debian'
      tags: sources.list

    - name: Create .ssh
      ansible.builtin.file:
        state: directory
        path: /home/humbertos/.ssh
        owner: humbertos
        group: humbertos
        mode: '0755'
      when: ansible_os_family == 'Debian'
      tags: ssh

    - name: Create ssh_config
      ansible.builtin.copy:
        content: |
          Host *
            User root
            StrictHostKeyChecking no
            IdentityFile ~/.ssh/id_ed25519
            KexAlgorithms +diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
            HostKeyAlgorithms +ssh-rsa,ssh-dss
            Ciphers +aes256-cbc
        dest: /home/humbertos/.ssh/config
        owner: humbertos
        group: humbertos
        mode: '0644'
        backup: true
      when: ansible_os_family == 'Debian'
      tags: ssh

    - name: Create /home/humbertos/.config/autostart/
      ansible.builtin.file:
        state: directory
        path: /home/humbertos/.config/autostart/
        owner: humbertos
        group: humbertos
        mode: '0755'
      when: ansible_os_family == 'Debian'
      tags: ssh

    - name: Create ssh-add.desktop
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Exec=ssh-add -q .ssh/id_rsa .ssh/id_ed25519
          Name=ssh-add
          Type=Application
        dest: /home/humbertos/.config/autostart/ssh-add.desktop
        owner: humbertos
        group: humbertos
        mode: '0755'
        backup: true
      when: ansible_os_family == 'Debian'
      tags: ssh

    - name: Create /home/humbertos/.config/environment.d/
      ansible.builtin.file:
        state: directory
        path: /home/humbertos/.config/environment.d/
        owner: humbertos
        group: humbertos
        mode: '0755'
      when: ansible_os_family == 'Debian'
      tags: ssh

    - name: Create ssh_askpass.conf
      ansible.builtin.copy:
        content: |
          SSH_ASKPASS=/usr/bin/ksshaskpass
          SSH_ASKPASS_REQUIRE=prefer
        dest: /home/humbertos/.config/environment.d/ssh_askpass.conf
        owner: humbertos
        group: humbertos
        mode: '0755'
        backup: true
      when: ansible_os_family == 'Debian'
      tags: ssh

    - name: Create .gitconfig
      ansible.builtin.copy:
        content: |
          [user]
            name = 85humberto
            email = 85humberto@gmail.com
        dest: /home/humbertos/.gitconfig
        owner: humbertos
        group: humbertos
        mode: '0644'
        backup: true
      when: ansible_os_family == 'Debian'

    - name: Create .ansible.cfg
      ansible.builtin.copy:
        content: |
          [defaults]
          interpreter_python=auto_silent
          collections_paths=collections
          forks=50
        dest: /home/humbertos/.ansible.cfg
        owner: humbertos
        group: humbertos
        mode: '0644'
        backup: true
      when: ansible_os_family == 'Debian'

    - name: Add the user 'humbertos' with a bash shell, appending the group 'sudo'
      ansible.builtin.user:
        name: humbertos
        groups: sudo
        append: true
      when: ansible_os_family == 'Debian'

    - name: No password prompt for sudo user
      ansible.builtin.copy:
        content: |
          %sudo ALL=(ALL) NOPASSWD: ALL
        dest: /etc/sudoers.d/nopasswd
        owner: root
        group: root
        mode: '0440'
        backup: true
      when: ansible_os_family == 'Debian'

    - name: Script to disable IPv6
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6
          echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
        dest: /usr/local/bin/disable_ipv6
        owner: root
        group: root
        mode: '0755'
      when: ansible_os_family == 'Debian'

    - name: Script to enable IPv6
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          echo 0 > /proc/sys/net/ipv6/conf/default/disable_ipv6
          echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
        dest: /usr/local/bin/enable_ipv6
        owner: root
        group: root
        mode: '0755'
      when: ansible_os_family == 'Debian'

    - name: Uninstall multiple packages
      ansible.builtin.apt:
        state: absent
        pkg:
          - snapd
          - thunderbird
          - kate
          - kmahjongg
          - kmines
          - ksudoku
          - kpat
      when: ansible_os_family == 'Debian'
      tags: uninstall_packages

    - name: Install multiple packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - vlc
          - unrar
          - nmap
          - mtr
          - traceroute
          - xournal
          - ipcalc
          - bash-completion
          - git
          - dnsutils
          - ldap-utils
          - flatpak
          - make
          - ansible-lint
          - snmp
          - command-not-found
          - tcpdump
          - telnet
          - zsh
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - podman
          - nautilus-dropbox
          - curl
          - ksshaskpass
          - virt-manager
          - libvirt-daemon-system
          - network-manager-openvpn
          - kwrite
      when: ansible_os_family == 'Debian'
      tags: install_packages

    - name: Appending the group libvirt and libvirt-qemu
      ansible.builtin.user:
        name: humbertos
        groups: "{{ item }}"
        append: true
      loop:
        - libvirt-qemu
        - libvirt
      when: ansible_os_family == 'Debian'

    - name: Set .zshrc
      ansible.builtin.copy:
        src: .zshrc
        dest: /home/humbertos/.zshrc
        owner: humbertos
        group: humbertos
        mode: '0644'
      when: ansible_os_family == 'Debian'
      tags: zshrc

    - name: Change owner
      ansible.builtin.file:
        path: /home/humbertos/.ansible.cfg
        owner: humbertos
        group: humbertos
      when: ansible_os_family == 'Debian'

    - name: Change owner
      ansible.builtin.file:
        path: /home/humbertos/.ansible/
        owner: humbertos
        group: humbertos
        recurse: true
      when: ansible_os_family == 'Debian'

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      when: (ansible_os_family == 'Debian')

    - name: Install multiple packages from flathub
      community.general.flatpak:
        name:
          - com.discordapp.Discord
          - com.authy.Authy
          - com.anydesk.Anydesk
          - org.mozilla.firefox
      when: (ansible_os_family == 'Debian')
      tags: flatpak

    - name: Override flatpak packages
      ansible.builtin.shell: |
        sudo flatpak override com.authy.Authy --filesystem=host
        sudo flatpak override org.mozilla.firefox --filesystem=host
      when: (ansible_os_family == 'Debian')
      tags: flatpak_override

    # TeamViewer
    - name: Add repository key TeamViewer
      ansible.builtin.apt_key:
        url: https://linux.teamviewer.com/pubkey/currentkey.asc
        state: present
        keyring: /usr/share/keyrings/teamviewer-keyring.gpg
      when: ansible_os_family == 'Debian'
      tags: teamviewer

    - name: Add repository TeamViewer
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/teamviewer-keyring.gpg] https://linux.teamviewer.com/deb stable main"
        filename: teamviewer
      when: ansible_os_family == 'Debian'
      tags: teamviewer

    - name: Install TeamViewer
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - teamviewer
      when: ansible_os_family == 'Debian'
      tags: teamviewer

    # VSCodium
    - name: Add repository key VSCodium
      ansible.builtin.apt_key:
        url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        keyring: /usr/share/keyrings/vscodium-archive-keyring.gpg
      when: ansible_os_family == 'Debian'
      tags: vscodium

    - name: Add repository VSCodium
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main"
        filename: vscodium
      when: ansible_os_family == 'Debian'
      tags: vscodium

    - name: Install VSCodium
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - codium
      when: ansible_os_family == 'Debian'
      tags: vscodium

    - name: Instalar o .deb warsaw - Linux Debian
      ansible.builtin.apt:
        deb: https://cloud.gastecnologia.com.br/bb/downloads/ws/warsaw_setup64.deb
      when: ansible_os_family == 'Debian'
      tags: warsaw
